apiVersion: v2
name: clearml
version: 26.2.4
type: application
appVersion: "2.4.0-722"

dependencies:
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 25.3.0
    condition: redis.enabled

  - name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.5.0
    condition: mongodb.enabled

  - name: elasticsearch
    repository: "https://wiremind.github.io/wiremind-helm-charts"
    version: 8.17.0
    condition: elasticsearch.enabled
